language: node_js
node_js:
  - "5.8.0"
before_script:
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - xz -d /tmp/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - tar -xvf /tmp/casper.tar
  - export PATH=$PATH:$PWD/wkhtmltox/bin/